-------------------------------------------------------------
-- STRICT AUTHENTICATION ROW LEVEL SECURITY (RLS) FOR SUPABASE
-------------------------------------------------------------
-- This script replaces the temporary "USING (true)" bypass you used during testing.
-- It locks down the entire database so only the exactly logged-in user can access 
-- their specific client shards.

-- 1. Remove the old relaxed bypass policies
DROP POLICY IF EXISTS "Allow anon select based on client_id" ON projects;
DROP POLICY IF EXISTS "Allow anon insert based on client_id" ON projects;
DROP POLICY IF EXISTS "Allow anon update based on client_id" ON projects;
DROP POLICY IF EXISTS "Allow anon delete based on client_id" ON projects;

DROP POLICY IF EXISTS "Allow anon select based on client_id" ON transactions;
DROP POLICY IF EXISTS "Allow anon insert based on client_id" ON transactions;
DROP POLICY IF EXISTS "Allow anon update based on client_id" ON transactions;
DROP POLICY IF EXISTS "Allow anon delete based on client_id" ON transactions;

DROP POLICY IF EXISTS "Allow anon select based on client_id" ON ponds;
DROP POLICY IF EXISTS "Allow anon insert based on client_id" ON ponds;
DROP POLICY IF EXISTS "Allow anon update based on client_id" ON ponds;
DROP POLICY IF EXISTS "Allow anon delete based on client_id" ON ponds;

DROP POLICY IF EXISTS "Allow anon select based on client_id" ON alerts;
DROP POLICY IF EXISTS "Allow anon insert based on client_id" ON alerts;
DROP POLICY IF EXISTS "Allow anon update based on client_id" ON alerts;
DROP POLICY IF EXISTS "Allow anon delete based on client_id" ON alerts;

DROP POLICY IF EXISTS "Allow anon select based on client_id" ON budgets;
DROP POLICY IF EXISTS "Allow anon insert based on client_id" ON budgets;
DROP POLICY IF EXISTS "Allow anon update based on client_id" ON budgets;
DROP POLICY IF EXISTS "Allow anon delete based on client_id" ON budgets;

DROP POLICY IF EXISTS "Allow anon select based on client_id" ON employees;
DROP POLICY IF EXISTS "Allow anon insert based on client_id" ON employees;
DROP POLICY IF EXISTS "Allow anon update based on client_id" ON employees;
DROP POLICY IF EXISTS "Allow anon delete based on client_id" ON employees;

DROP POLICY IF EXISTS "Allow anon select based on client_id" ON attendance;
DROP POLICY IF EXISTS "Allow anon insert based on client_id" ON attendance;
DROP POLICY IF EXISTS "Allow anon update based on client_id" ON attendance;
DROP POLICY IF EXISTS "Allow anon delete based on client_id" ON attendance;

-- 2. Apply Strict `auth.uid()` Matching
-- `auth.uid()` fetches the immutable UUID generated by your Google Authentication.
-- We cast client_id to UUID (if you used text fields, they should map appropriately)

CREATE POLICY "Strict user isolation" ON projects FOR ALL USING (auth.uid()::text = client_id);
CREATE POLICY "Strict user isolation" ON transactions FOR ALL USING (auth.uid()::text = client_id);
CREATE POLICY "Strict user isolation" ON ponds FOR ALL USING (auth.uid()::text = client_id);
CREATE POLICY "Strict user isolation" ON alerts FOR ALL USING (auth.uid()::text = client_id);
CREATE POLICY "Strict user isolation" ON budgets FOR ALL USING (auth.uid()::text = client_id);
CREATE POLICY "Strict user isolation" ON employees FOR ALL USING (auth.uid()::text = client_id);
CREATE POLICY "Strict user isolation" ON attendance FOR ALL USING (auth.uid()::text = client_id);

-- Wait, the `client_id` parameter in your earlier schema was defined as `TEXT`. 
-- `auth.uid()` natively returns `uuid`. Coercing the `uuid` into `text` via `::text` safely satisfies this.
