
import { db } from '../src/lib/firebase';
import { ref, set } from 'firebase/database';

const transactions = [
    {
        "id": "1",
        "date": "2025-09-08T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5001",
        "title": "Miscellaneous Expenses",
        "amount": 90000,
        "quantity": 1,
        "unit": "AU",
        "ratePerUnit": 0,
        "vendor": "Multiple",
        "description": "for Clearing the weed , Errecting the coconut plants",
        "notes": "Spent by Mom on our behalf",
        "category": "Miscellaneous Expenses",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "2",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 45200,
        "quantity": 20,
        "unit": "EA",
        "ratePerUnit": 45180,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "5' Supreme C Singe Pipes",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "3",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 37000,
        "quantity": 1,
        "unit": "EA",
        "ratePerUnit": 37000,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "5HP Pump Set",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "4",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 2150,
        "quantity": 65,
        "unit": "M",
        "ratePerUnit": 33,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "L&T Starter 9-14A",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "5",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 7150,
        "quantity": 60,
        "unit": "M",
        "ratePerUnit": 119,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "2.5 Sqmm 3 core flat cable",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "6",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 17400,
        "quantity": 60,
        "unit": "M",
        "ratePerUnit": 290,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "75mm supreme 8 kg hdpe Pipe",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "7",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 2000,
        "quantity": 2,
        "unit": "EA",
        "ratePerUnit": 1000,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "75mm Hdhpe ss nipple",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "8",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 550,
        "quantity": 2,
        "unit": "EA",
        "ratePerUnit": 275,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "75mm Iron Clamps",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "9",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 1000,
        "quantity": 1,
        "unit": "Au",
        "ratePerUnit": 1000,
        "vendor": "Auto",
        "description": "Transport of Pump, Pipes",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "10",
        "date": "2025-07-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 22000,
        "quantity": 200,
        "unit": "FT",
        "ratePerUnit": 110,
        "vendor": "Lakshmi Bore Works - Ravulapalem",
        "description": "Drilling Bore - 6\" Bore @ 200 Feet @110/Foot",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "11",
        "date": "2025-07-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 5250,
        "quantity": 35,
        "unit": "Bags",
        "ratePerUnit": 150,
        "vendor": "Lakshmi Bore Works - Ravulapalem",
        "description": "Round Pebbles @150/Bag",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "12",
        "date": "2025-07-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 900,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 900,
        "vendor": "Lakshmi Bore Works - Ravulapalem",
        "description": "Labour Cost for Unloading Material",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "13",
        "date": "2025-08-30T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5003",
        "title": "Road Work",
        "amount": 20200,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 20200,
        "vendor": "JCB Vendor",
        "description": "JCB 5.10 hrs @ 1200 , Tractor 4 Trips @ 3500, Diesel , Beta",
        "notes": "Road Work - Services",
        "category": "Road Work",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "14",
        "date": "2025-08-30T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5003",
        "title": "Road Work",
        "amount": 30000,
        "quantity": 3,
        "unit": "EA",
        "ratePerUnit": 10000,
        "vendor": "Quarry",
        "description": "Gravel Boulders 3 Trucks @10,000 / Truck",
        "notes": "Road Work - Materials",
        "category": "Road Work",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "15",
        "date": "2025-08-31T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5003",
        "title": "Road Work",
        "amount": 12800,
        "quantity": 1,
        "unit": "EA",
        "ratePerUnit": 12800,
        "vendor": "Quarry",
        "description": "Gravel Dust 1 Trucks @13,000 / Truck",
        "notes": "Road Work - Materials",
        "category": "Road Work",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "16",
        "date": "2025-08-31T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5003",
        "title": "Road Work",
        "amount": 800,
        "quantity": 4,
        "unit": "EA",
        "ratePerUnit": 200,
        "vendor": "Truck Driver",
        "description": "200/Truck Driver Beta",
        "notes": "Road Work - Service",
        "category": "Road Work",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "17",
        "date": "2025-08-31T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5003",
        "title": "Road Work",
        "amount": 2000,
        "quantity": 2,
        "unit": "EA",
        "ratePerUnit": 1000,
        "vendor": "Labour",
        "description": "Labour Cost for Laying the Road",
        "notes": "Road Work - Service",
        "category": "Road Work",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "18",
        "date": "2025-08-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 3000,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 3000,
        "vendor": "Abid Ali",
        "description": "Bore Digging Equipment Transporter",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "19",
        "date": "2025-08-29T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 1200,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 1200,
        "vendor": "Abid Ali",
        "description": "Pipe Extraction Equipment Transporter",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "20",
        "date": "2025-08-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 500,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 500,
        "vendor": "Abid Ali",
        "description": "Advance Payment",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "21",
        "date": "2025-08-28T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 5000,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 5000,
        "vendor": "Abid Ali",
        "description": "Advance Payment",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "22",
        "date": "2025-09-06T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 5000,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 5000,
        "vendor": "Abid Ali",
        "description": "Advance Payment",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "23",
        "date": "2025-08-29T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5012",
        "title": "Tree Cutting",
        "amount": 6500,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 6500,
        "vendor": "Tree Cuttter @500/ tree",
        "description": "Cutting Coconut trees",
        "notes": "Tree Cutting - Services",
        "category": "Tree Cutting",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "24",
        "date": "2025-08-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5014",
        "title": "IT Setup",
        "amount": 8500,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 8500,
        "vendor": "Godrej",
        "description": "Godrej Solar Camera",
        "notes": "IT-Infra - Materials",
        "category": "IT Setup",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "25",
        "date": "2025-08-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5014",
        "title": "IT Setup",
        "amount": 1000,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 1000,
        "vendor": "Welding",
        "description": "Godrej Solar Camera",
        "notes": "IT-Infra - Materials",
        "category": "IT Setup",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "26",
        "date": "2025-09-06T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 8000,
        "quantity": 8,
        "unit": "LS",
        "ratePerUnit": 1000,
        "vendor": "HPCL Petrol pump",
        "description": "Diesel for Bore Drilling (8 days)",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "27",
        "date": "2025-09-08T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 44800,
        "quantity": 25,
        "unit": "EA",
        "ratePerUnit": 1792,
        "vendor": "M/s Srinivasea Mill",
        "description": "Pipes",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "28",
        "date": "2025-09-08T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 10000,
        "quantity": 3,
        "unit": "EA",
        "ratePerUnit": 3333,
        "vendor": "M/s Srinivasea Mill",
        "description": "Pipes",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "29",
        "date": "2025-09-08T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 700,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 700,
        "vendor": "Venkateswara Rao",
        "description": "Transport of Pump, Pipes from Palakol to Agarru",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "30",
        "date": "2025-08-29T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5013",
        "title": "Labour",
        "amount": 25200,
        "quantity": 42,
        "unit": "Days",
        "ratePerUnit": 600,
        "vendor": "Rambabu Salary 42 days till 31st October",
        "description": "Salary",
        "notes": "Labour",
        "category": "Labour",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    },
    {
        "id": "31",
        "date": "2025-09-06T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5004",
        "title": "Weed Removal",
        "amount": 1100,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 1100,
        "vendor": "Weedremoval",
        "description": "Spray Weed revoer + labour + Spray Can Rent",
        "notes": "Labour",
        "category": "Weed Removal",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed"
    }
];

const budgets = [
    { "id": "1", "glCode": "5001", "category": "Miscellaneous Expenses", "budget": 100000 },
    { "id": "2", "glCode": "5002", "category": "Bore Construction", "budget": 60000 },
    { "id": "3", "glCode": "5003", "category": "Road Work", "budget": 0 },
    { "id": "4", "glCode": "5004", "category": "Weed Removal", "budget": 0 },
    { "id": "5", "glCode": "5005", "category": "LT Connection (Power)", "budget": 500000 },
    { "id": "6", "glCode": "5006", "category": "Electrical Equipments", "budget": 100000 },
    { "id": "7", "glCode": "5007", "category": "Pond Preparation", "budget": 0 },
    { "id": "8", "glCode": "5008", "category": "Seed", "budget": 0 },
    { "id": "9", "glCode": "5009", "category": "Feed", "budget": 0 },
    { "id": "10", "glCode": "5010", "category": "Transportation", "budget": 0 },
    { "id": "11", "glCode": "5011", "category": "Lab and Testing", "budget": 0 },
    { "id": "12", "glCode": "5012", "category": "Tree Cutting", "budget": 5000 },
    { "id": "13", "glCode": "5013", "category": "Labour", "budget": 0 },
    { "id": "14", "glCode": "5014", "category": "IT Setup", "budget": 8000 }
];

async function seedDatabase() {
    try {
        const transactionsRef = ref(db, 'transactions');
        const transactionsData: Record<string, any> = {};
        transactions.forEach(t => {
            const { id, ...rest } = t;
            transactionsData[id] = rest;
        });
        await set(transactionsRef, transactionsData);
        console.log('Transactions seeded successfully.');

        const budgetsRef = ref(db, 'budgets');
        const budgetsData: Record<string, any> = {};
        budgets.forEach(b => {
            const { id, ...rest } = b;
            budgetsData[id] = rest;
        });
        await set(budgetsRef, budgetsData);
        console.log('Budgets seeded successfully.');

    } catch (error) {
        console.error('Error seeding database:', error);
    }
}

seedDatabase();


    