
import { db } from '../src/lib/firebase';
import { ref, set } from 'firebase/database';

console.log(`
This is a destructive script that will overwrite the data in your Firebase Realtime Database.
It is intended for initial setup and not for migrating existing data.

If you want to update existing transactions (e.g., add the 'status' or 'projectId' field),
please use the migration script instead by running:

npm run migrate

To proceed with seeding and overwriting data, you must run this script with an explicit --force flag:

tsx scripts/seed.ts --force
`);

const force = process.argv.includes('--force');

if (!force) {
    console.log('Exiting: --force flag not provided.');
    process.exit(0);
}

const pondConstructionProjectId = "-NztBqYtA3So9WwL0d5V";
const farmExpansionProjectId = "-NztBqYtA3So9WwL0d5V";

const projects = [
    { id: pondConstructionProjectId, name: "Pond Construction" },
    { id: farmExpansionProjectId, name: "Pond Construction" }
];

const transactions = [
    {
        "id": "1",
        "date": "2025-09-08T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5001",
        "title": "Miscellaneous Expenses",
        "amount": 90000,
        "quantity": 1,
        "unit": "AU",
        "ratePerUnit": 0,
        "vendor": "Multiple",
        "description": "for Clearing the weed , Errecting the coconut plants",
        "notes": "Spent by Mom on our behalf",
        "category": "Miscellaneous Expenses",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "2",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 45200,
        "quantity": 20,
        "unit": "EA",
        "ratePerUnit": 45180,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "5' Supreme C Singe Pipes",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "3",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 37000,
        "quantity": 1,
        "unit": "EA",
        "ratePerUnit": 37000,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "5HP Pump Set",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "4",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 2150,
        "quantity": 65,
        "unit": "M",
        "ratePerUnit": 33,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "L&T Starter 9-14A",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "5",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 7150,
        "quantity": 60,
        "unit": "M",
        "ratePerUnit": 119,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "2.5 Sqmm 3 core flat cable",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "6",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 17400,
        "quantity": 60,
        "unit": "M",
        "ratePerUnit": 290,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "75mm supreme 8 kg hdpe Pipe",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "7",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 2000,
        "quantity": 2,
        "unit": "EA",
        "ratePerUnit": 1000,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "75mm Hdhpe ss nipple",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "8",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "VLG455/25",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 550,
        "quantity": 2,
        "unit": "EA",
        "ratePerUnit": 275,
        "vendor": "Vijay Lakshmi Engineering",
        "description": "75mm Iron Clamps",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "9",
        "date": "2025-07-25T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 1000,
        "quantity": 1,
        "unit": "Au",
        "ratePerUnit": 1000,
        "vendor": "Auto",
        "description": "Transport of Pump, Pipes",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "10",
        "date": "2025-07-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 22000,
        "quantity": 200,
        "unit": "FT",
        "ratePerUnit": 110,
        "vendor": "Lakshmi Bore Works - Ravulapalem",
        "description": "Drilling Bore - 6\" Bore @ 200 Feet @110/Foot",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "11",
        "date": "2025-07-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 5250,
        "quantity": 35,
        "unit": "Bags",
        "ratePerUnit": 150,
        "vendor": "Lakshmi Bore Works - Ravulapalem",
        "description": "Round Pebbles @150/Bag",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "12",
        "date": "2025-07-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 900,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 900,
        "vendor": "Lakshmi Bore Works - Ravulapalem",
        "description": "Labour Cost for Unloading Material",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "13",
        "date": "2025-08-30T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5003",
        "title": "Road Work",
        "amount": 20200,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 20200,
        "vendor": "JCB Vendor",
        "description": "JCB 5.10 hrs @ 1200 , Tractor 4 Trips @ 3500, Diesel , Beta",
        "notes": "Road Work - Services",
        "category": "Road Work",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "14",
        "date": "2025-08-30T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5003",
        "title": "Road Work",
        "amount": 30000,
        "quantity": 3,
        "unit": "EA",
        "ratePerUnit": 10000,
        "vendor": "Quarry",
        "description": "Gravel Boulders 3 Trucks @10,000 / Truck",
        "notes": "Road Work - Materials",
        "category": "Road Work",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "15",
        "date": "2025-08-31T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5003",
        "title": "Road Work",
        "amount": 12800,
        "quantity": 1,
        "unit": "EA",
        "ratePerUnit": 12800,
        "vendor": "Quarry",
        "description": "Gravel Dust 1 Trucks @13,000 / Truck",
        "notes": "Road Work - Materials",
        "category": "Road Work",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "16",
        "date": "2025-08-31T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5003",
        "title": "Road Work",
        "amount": 800,
        "quantity": 4,
        "unit": "EA",
        "ratePerUnit": 200,
        "vendor": "Truck Driver",
        "description": "200/Truck Driver Beta",
        "notes": "Road Work - Service",
        "category": "Road Work",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "17",
        "date": "2025-08-31T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5003",
        "title": "Road Work",
        "amount": 2000,
        "quantity": 2,
        "unit": "EA",
        "ratePerUnit": 1000,
        "vendor": "Labour",
        "description": "Labour Cost for Laying the Road",
        "notes": "Road Work - Service",
        "category": "Road Work",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "18",
        "date": "2025-08-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 3000,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 3000,
        "vendor": "Abid Ali",
        "description": "Bore Digging Equipment Transporter",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "19",
        "date": "2025-08-29T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 1200,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 1200,
        "vendor": "Abid Ali",
        "description": "Pipe Extraction Equipment Transporter",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "20",
        "date": "2025-08-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 500,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 500,
        "vendor": "Abid Ali",
        "description": "Advance Payment",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "21",
        "date": "2025-08-28T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 5000,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 5000,
        "vendor": "Abid Ali",
        "description": "Advance Payment",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "22",
        "date": "2025-09-06T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 5000,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 5000,
        "vendor": "Abid Ali",
        "description": "Advance Payment",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "23",
        "date": "2025-08-29T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5012",
        "title": "Tree Cutting",
        "amount": 6500,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 6500,
        "vendor": "Tree Cuttter @500/ tree",
        "description": "Cutting Coconut trees",
        "notes": "Tree Cutting - Services",
        "category": "Tree Cutting",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "24",
        "date": "2025-08-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5014",
        "title": "IT Setup",
        "amount": 8500,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 8500,
        "vendor": "Godrej",
        "description": "Godrej Solar Camera",
        "notes": "IT-Infra - Materials",
        "category": "IT Setup",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "25",
        "date": "2025-08-27T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5014",
        "title": "IT Setup",
        "amount": 1000,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 1000,
        "vendor": "Welding",
        "description": "Godrej Solar Camera",
        "notes": "IT-Infra - Materials",
        "category": "IT Setup",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "26",
        "date": "2025-09-06T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 8000,
        "quantity": 8,
        "unit": "LS",
        "ratePerUnit": 1000,
        "vendor": "HPCL Petrol pump",
        "description": "Diesel for Bore Drilling (8 days)",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "27",
        "date": "2025-09-08T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 44800,
        "quantity": 25,
        "unit": "EA",
        "ratePerUnit": 1792,
        "vendor": "M/s Srinivasea Mill",
        "description": "Pipes",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "28",
        "date": "2025-09-08T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 10000,
        "quantity": 3,
        "unit": "EA",
        "ratePerUnit": 3333,
        "vendor": "M/s Srinivasea Mill",
        "description": "Pipes",
        "notes": "Bore - Materials",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "29",
        "date": "2025-09-08T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5002",
        "title": "Bore Construction",
        "amount": 700,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 700,
        "vendor": "Venkateswara Rao",
        "description": "Transport of Pump, Pipes from Palakol to Agarru",
        "notes": "Bore - Services",
        "category": "Bore Construction",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "30",
        "date": "2025-08-29T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5013",
        "title": "Labour",
        "amount": 25200,
        "quantity": 42,
        "unit": "Days",
        "ratePerUnit": 600,
        "vendor": "Rambabu Salary 42 days till 31st October",
        "description": "Salary",
        "notes": "Labour",
        "category": "Labour",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "31",
        "date": "2025-09-06T00:00:00.000Z",
        "createdAt": "2024-07-31T12:00:00.000Z",
        "invoiceNo": "Nil",
        "glCode": "5004",
        "title": "Weed Removal",
        "amount": 1100,
        "quantity": 1,
        "unit": "LS",
        "ratePerUnit": 1100,
        "vendor": "Weedremoval",
        "description": "Spray Weed revoer + labour + Spray Can Rent",
        "notes": "Labour",
        "category": "Weed Removal",
        "receiptUrl": "",
        "createdBy": "Vijay",
        "type": "expense",
        "status": "completed",
        "projectId": pondConstructionProjectId
    },
    {
        "id": "-OZitWWQ82g82dZBXJ6h",
        "amount": 312883,
        "category": "LT Connection (Power)",
        "createdAt": "2025-09-09T14:34:15.537Z",
        "createdBy": "Vijay",
        "date": "2025-09-09T00:00:00.000Z",
        "description": "new 25KVa Power Connection ",
        "glCode": "",
        "invoiceNo": "GPay ",
        "notes": "new 25KVa Power Connection ",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "completed",
        "title": "new 25KVa Power Connection ",
        "type": "expense",
        "unit": "",
        "vendor": "APEPDCL",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZjYvC0_BSUWdC-HrPx",
        "amount": 25000,
        "category": "Bore Construction",
        "createdAt": "2025-09-09T17:39:30.788Z",
        "createdBy": "Vijay",
        "date": "2025-09-09T00:00:00.000Z",
        "description": "Bore digging work",
        "glCode": "",
        "invoiceNo": "Gpay",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "completed",
        "title": "Part payment for bore work-Part Payment ",
        "type": "expense",
        "unit": "",
        "vendor": "Abid Ali",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZjZNAfjba7COvbRtLD",
        "amount": 40000,
        "category": "LT Connection (Power)",
        "createdAt": "2025-09-09T17:41:29.486Z",
        "createdBy": "Vijay",
        "date": "2025-09-09T00:00:00.000Z",
        "description": "Extra Amount ",
        "glCode": "",
        "invoiceNo": "Mom",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "credit",
        "title": "25 KVA LT power connection Extra Amount",
        "type": "expense",
        "unit": "",
        "vendor": "AE",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZjZwO9TlgbPKzcUDAr",
        "amount": 2000,
        "category": "Weed Removal",
        "createdAt": "2025-09-09T17:43:57.805Z",
        "createdBy": "Vijay",
        "date": "2025-09-09T00:00:00.000Z",
        "description": "2 workers @ 1000/ person ",
        "glCode": "",
        "invoiceNo": "Mom",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "credit",
        "title": "Labour for De weeding ",
        "type": "expense",
        "unit": "",
        "vendor": "",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZj_qdhCglkI3bKUVjS",
        "amount": 2000,
        "category": "Bore Construction",
        "createdAt": "2025-09-09T17:47:56.432Z",
        "createdBy": "Vijay",
        "date": "2025-09-08T00:00:00.000Z",
        "description": "Chicken , surf, cold drink , hot drink",
        "glCode": "",
        "invoiceNo": "Mom",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "credit",
        "title": "Bore Worker’s extra payment  ",
        "type": "expense",
        "unit": "",
        "vendor": "Party ",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZjaR9O_7tKguNdP_1E",
        "amount": 1000,
        "category": "Bore Construction",
        "createdAt": "2025-09-09T17:50:30.076Z",
        "createdBy": "Vijay",
        "date": "2025-09-08T00:00:00.000Z",
        "description": "",
        "glCode": "",
        "invoiceNo": "Mom",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "credit",
        "title": "Diesel for Bore Drilling",
        "type": "expense",
        "unit": "",
        "vendor": "",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZjcrR3xf78ooF8mleV",
        "amount": 2000,
        "category": "Weed Removal",
        "createdAt": "2025-09-09T18:01:06.087Z",
        "createdBy": "Vijay",
        "date": "2025-09-08T00:00:00.000Z",
        "description": "Around",
        "glCode": "",
        "invoiceNo": "Mom",
        "notes": "The pond",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "credit",
        "title": "De-weeding ",
        "type": "expense",
        "unit": "",
        "vendor": "",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZjleCU_PQI_2rAnA4W",
        "amount": 6000,
        "category": "Labour",
        "createdAt": "2025-09-09T18:39:31.204Z",
        "createdBy": "Vijay",
        "date": "2025-09-10T00:00:00.000Z",
        "description": "1sept to 10th September ",
        "glCode": "",
        "invoiceNo": "",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "expected",
        "title": "Salary",
        "type": "expense",
        "unit": "",
        "vendor": "Rambabu ",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZlQHG5R-JV5Z0hkClp",
        "amount": 6500,
        "category": "Bore Construction",
        "createdAt": "2025-09-10T02:21:00.385Z",
        "createdBy": "Vijay",
        "date": "2025-09-08T00:00:00.000Z",
        "description": "",
        "glCode": "",
        "invoiceNo": "",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "completed",
        "title": "Pebble’s for Bore @2nd point",
        "type": "expense",
        "unit": "",
        "vendor": "Gulaka Rallu",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZnfFjrq-bcDcSZxHNl",
        "amount": 5000,
        "category": "Bore Construction",
        "createdAt": "2025-09-10T12:50:02.903Z",
        "createdBy": "Vijay",
        "date": "2025-08-13T00:00:00.000Z",
        "description": "Bore point ",
        "glCode": "",
        "invoiceNo": "",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "completed",
        "title": "Geo Survey for Bore point selection ",
        "type": "expense",
        "unit": "",
        "vendor": "",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZqu6wKRPTId5XO83HQ",
        "amount": 6000,
        "category": "Bore Construction",
        "createdAt": "2025-09-11T03:53:50.292Z",
        "createdBy": "Vijay",
        "date": "2025-07-24T00:00:00.000Z",
        "description": "",
        "glCode": "",
        "invoiceNo": "",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "completed",
        "title": "Diesel for Bore Digging ",
        "type": "expense",
        "unit": "",
        "vendor": "",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZquT1DIWTJw8F_KioJ",
        "amount": 2000,
        "category": "Bore Construction",
        "createdAt": "2025-09-11T03:55:20.782Z",
        "createdBy": "Vijay",
        "date": "2025-07-24T00:00:00.000Z",
        "description": "",
        "glCode": "",
        "invoiceNo": "",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "completed",
        "title": "Bore Digging Equipment Transportation Charges ",
        "type": "expense",
        "unit": "",
        "vendor": "",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZquoz-E5EsCJVA46Qp",
        "amount": 5000,
        "category": "Bore Construction",
        "createdAt": "2025-09-11T03:56:54.784Z",
        "createdBy": "Vijay",
        "date": "2025-07-24T00:00:00.000Z",
        "description": "",
        "glCode": "",
        "invoiceNo": "",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "completed",
        "title": "Food Expenses for Bore Digging Workers ",
        "type": "expense",
        "unit": "",
        "vendor": "Bore 1",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZsS_1KfekFfHKKPrBD",
        "amount": 2300,
        "category": "Weed Removal",
        "createdAt": "2025-09-11T11:08:22.068Z",
        "createdBy": "Vijay",
        "date": "2025-09-11T00:00:00.000Z",
        "description": "",
        "glCode": "",
        "invoiceNo": "",
        "notes": "",
        "quantity": 2,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "credit",
        "title": "Weed clearing @ adda gattu ",
        "type": "expense",
        "unit": "Persons",
        "vendor": "",
        "projectId": farmExpansionProjectId
    },
    {
        "id": "-OZsSqizLya2DEStX6NA",
        "amount": 22000,
        "category": "Bore Construction",
        "createdAt": "2025-09-11T11:09:34.559Z",
        "createdBy": "Vijay",
        "date": "2025-09-11T00:00:00.000Z",
        "description": "",
        "glCode": "",
        "invoiceNo": "",
        "notes": "",
        "quantity": 0,
        "ratePerUnit": 0,
        "receiptUrl": "",
        "status": "expected",
        "title": "Balance Payment to Abid Ali",
        "type": "expense",
        "unit": "",
        "vendor": "",
        "projectId": farmExpansionProjectId
    }
];

const budgets = [
    { "id": "b1", "glCode": "5001", "category": "Miscellaneous Expenses", "budget": 50000, "projectId": pondConstructionProjectId },
    { "id": "b2", "glCode": "5002", "category": "Bore Construction", "budget": 160000, "projectId": pondConstructionProjectId },
    { "id": "b3", "glCode": "5003", "category": "Road Work", "budget": 50000, "projectId": pondConstructionProjectId },
    { "id": "b4", "glCode": "5004", "category": "Weed Removal", "budget": 8000, "projectId": pondConstructionProjectId },
    { "id": "b5", "glCode": "5005", "category": "LT Connection (Power)", "budget": 500000, "projectId": pondConstructionProjectId },
    { "id": "b6", "glCode": "5006", "category": "Electrical Equipments", "budget": 100000, "projectId": pondConstructionProjectId },
    { "id": "b7", "glCode": "5007", "category": "Pond Preparation", "budget": 0, "projectId": pondConstructionProjectId },
    { "id": "b8", "glCode": "5008", "category": "Seed", "budget": 0, "projectId": pondConstructionProjectId },
    { "id": "b9", "glCode": "5009", "category": "Feed", "budget": 0, "projectId": pondConstructionProjectId },
    { "id": "b10", "glCode": "5010", "category": "Transportation", "budget": 0, "projectId": pondConstructionProjectId },
    { "id": "b11", "glCode": "5011", "category": "Lab and Testing", "budget": 0, "projectId": pondConstructionProjectId },
    { "id": "b12", "glCode": "5012", "category": "Tree Cutting", "budget": 5000, "projectId": pondConstructionProjectId },
    { "id": "b13", "glCode": "5013", "category": "Labour", "budget": 0, "projectId": pondConstructionProjectId },
    { "id": "b14", "glCode": "5014", "category": "IT Setup", "budget": 8000, "projectId": pondConstructionProjectId },

    // Budgets for Farm Expansion Project
    { "id": "b15", "glCode": "", "category": "LT Connection (Power)", "budget": 0, "projectId": farmExpansionProjectId },
    { "id": "b16", "glCode": "", "category": "Bore Construction", "budget": 0, "projectId": farmExpansionProjectId },
    { "id": "b17", "glCode": "", "category": "Weed Removal", "budget": 0, "projectId": farmExpansionProjectId },
    { "id": "b18", "glCode": "", "category": "Labour", "budget": 0, "projectId": farmExpansionProjectId },

];

async function seedDatabase() {
    try {
        const projectsRef = ref(db, 'projects');
        const projectsData: Record<string, any> = {};
        projects.forEach(p => {
            const { id, ...rest } = p;
            projectsData[id] = rest;
        });
        await set(projectsRef, projectsData);
        console.log('Projects seeded successfully.');

        const transactionsRef = ref(db, 'transactions');
        const transactionsData: Record<string, any> = {};
        transactions.forEach(t => {
            const { id, ...rest } = t;
            transactionsData[id] = rest;
        });
        await set(transactionsRef, transactionsData);
        console.log('Transactions seeded successfully.');

        const budgetsRef = ref(db, 'budgets');
        const budgetsData: Record<string, any> = {};
        budgets.forEach(b => {
            const { id, ...rest } = b;
            budgetsData[id] = rest;
        });
        await set(budgetsRef, budgetsData);
        console.log('Budgets seeded successfully.');

    } catch (error) {
        console.error('Error seeding database:', error);
        process.exit(1);
    } finally {
        // The script hangs without this.
        process.exit(0);
    }
}

seedDatabase();

    